### PR TITLE
Fix spelling & grammar mistakes, change package naming, and some other misc. changes

### PR DESCRIPTION
**Pull request by triphora**

### CODE REVIEW

**Review by Blobanium — CHANGES_REQUESTED** [review]
can you add back the mixin files? after some playtesting the mod kinda doesn't work at all because you deleted the mixin. The mixin you deleted calls the [main function](https://github.com/Blobanium/Loading-Timer/blob/e934dfe320a3418d1252baa848f8c5e7dcb12d20/src/main/java/net/blobanium/example/mixin/ExampleMixin.java#L16) of this mod. Which is probably what the entire mod relies on. If there's no mixin, there's basically nothing that can call that function, causing the mod to not work at all. Everything else is looking good.

**Comment by triphora** [comment]
I would advise against using ExampleMixin as the name of a critical component. :stuck_out_tongue: Re-added, with the name LoadModMixin

**Comment by Blobanium** [comment]
eek!
Capture

you might wanna fix that, i can also fix if you want me to.

**Comment by triphora** [comment]
Hold on, still doesn't work... gimme a min

**Comment by triphora** [comment]
Git doesn't like me. Will make a new PR (#6)

**Pull request closed without merging**
